### PR TITLE
Add that AXRoleDescription and AXCustomContent value are localizable strings

### PR DESCRIPTION
**Pull request by mattgarrish**
Adds the modified version of the note from core-aam specification described in https://github.com/w3c/dpub-aam/issues/18#issuecomment-1372722694

Also adds a space after the "AXCustomContent" label in the tables.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/dpub-aam/pull/20.html" title="Last updated on Jan 13, 2023, 3:30 PM UTC (9d9be09)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/dpub-aam/20/f500b9d...9d9be09.html" title="Last updated on Jan 13, 2023, 3:30 PM UTC (9d9be09)">Diff</a>

### CODE REVIEW

**Review by cookiecrook — CHANGES_REQUESTED** [review]
I think this should be a new normative section matching Translatable Attributes in the ARIA and HTML Specs. 

https://w3c.github.io/aria/#translatable-attributes


Editorial Nit: I would keep this PR for the white space changes, roll back the note, and file a new issue for the new section.

**Comment by mattgarrish** [comment]
Thanks, @cookiecrook, I'll try to look into your suggestion this week.

I've incorporated the whitespace fix into the main branch as it's not significant to the text and merged the update back into this branch so I can keep it for the eventual fix. This way we can keep the discussion intact.

**Comment by mattgarrish** [comment]
Let me know if this is better @cookiecrook.

I tried my best to adapt the section you pointed to, but not sure if I've got the right mix of translatable attributes with this being translatable mapping strings.

**Review by cookiecrook — APPROVED** [review]
This looks good to me. Thanks. I now further understand the awkwardness of trying to take a spec "translatable attributes" section and squeeze it into an AAM. Sorry I didn't think that far ahead when I made the prior comment, but I think you've done a good job reinterpreting as necessary.

**Pull request merged**
